### ISSUE TITLE
LV3 코드리뷰

### ISSUE THREAD

**Issue by 9sanha** [Chunws13/Nodejs_study#4]
고생하셨습니다!!

1. blog와 post가 왜 분리되어 있을까요? erd가 없어서 파악이 어렵습니다!
userId 연관관계에 따라 의도적으로 분리하신것일까요?

2.컬럼명은 fk여도 보통 소문자로 시작합니다! 
<img width="386" alt="image" src="https://github.com/Chunws13/Nodejs_study/assets/64877575/92ecbffd-2478-4eec-a6f6-f85cc4383f34">

3. blog 게시글 수정시 수정 일자도 같이 업데이트 해주도록 수정되어야합니다!

4. 추가적으로, 데이터를 삭제할 때 물리적으로 삭제(hard delete)하는 것과 논리적으로 삭제(soft delete)하는 방법이 있습니다!
추후에는 이런 부분도 같이 고민해보시면 좋을 것 같아 공유드려요!

**Comment by Chunws13** [comment]
1. routes 폴더 내 Post 파일은 수업 따라 듣기 용도로 만들었으나 업로드 과정에서 착오가 있어 같이 업로드 되었습니다. 레퍼지토리 최신화 진행했습니다.

2. 별도 지식이 없어 강의 내용따라서 변수명을 통일했습니다. 이후에는 동일하게 소문자로 진행하겠습니다.

3. 수정 발행 시, 수정 시간 업데이트 되도록 설정했습니다.

4. 물리적 삭제와 논리적 삭제 관련된 내용 한번 찾아보겠습니다.

감사합니다!
